# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    run_tests(scheme: "NeuroID")
  end
  desc "Update project version"
  lane :update_version do
    version = version_bump_podspec(path: "Neuro-ID.podspec", version_number: ENV["newVersion"])
    currentversion = get_version_number(
    xcodeproj: "Project.xcodeproj",
    target: "App"
    )
    if currentversion != ENV["newVersion"]
      increment_version_number(
      version_number: ENV["newVersion"],      # specify specific version number (optional, omitting it increments patch version number)
      xcodeproj: "./NeuroID.xcodeproj"  
      )
    else
      UI.error "The project version is the same as the new version" 
    end
  end
end
