# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Schema Tests"
  lane :test do
    run_tests(
      scheme: "NeuroID",
      project: "NeuroID.xcodeproj",
      clean: true,
      destination: "platform=iOS Simulator,name=iPhone 17 Pro,OS=latest",
      configuration: "Debug",
      xcargs: "CODE_SIGNING_ALLOWED=NO",
    )
  end

  desc "Update project version"
  lane :update_version do
    version = version_bump_podspec(path: "NeuroID.podspec", version_number: ENV["newVersion"])
    currentversion = get_version_number(
    xcodeproj: "NeuroID.xcodeproj",
    target: "NeuroID"
    )
    if currentversion != ENV["newVersion"]
      increment_version_number(
      version_number: ENV["newVersion"],      # specify specific version number (optional, omitting it increments patch version number)
      xcodeproj: "./NeuroID.xcodeproj"  
      )
    else
      UI.error "The project version is the same as the new version" 
    end
  end

  desc "Update Podfile and Plist Version"
  lane :update_project_version do
    version_bump_podspec(path: "NeuroID.podspec", bump_type: ENV["releaseType"])
    increment_version_number(bump_type: ENV["releaseType"])
  end

  desc "Prints the version number"
  lane :get_project_version do
    version_number = get_version_number(xcodeproj: "NeuroID.xcodeproj", target:"NeuroID")
    UI.message "SDK Version: #{version_number}"
  end
end
