on:
  workflow_dispatch:
    inputs:
      version_checker:
        description: 'Enter title'
        required: true
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          v=`echo $version | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/'`
          echo "Version number $v"
          if [ "$version" = "$v" ]; then
              echo "-1"
          else
              echo "$v"
          fi
        env:
          version: ${{ inputs.version_checker }}

