name: Github Actions for iOS NeuroID SDK

on:
  push:
    branches:
      - main
      - master
      - 'ENG-17-github-actions-for-neuroid-ios-sdk'
      
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up ruby env
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: 2.7.2
        
      - name: Run unit testing
        uses: bundle exec fastlane test
​
