name: Github Actions for iOS NeuroID SDK

on:
  push:
    branches:
      - main
      - master
      - release/*
  repository_dispatch:
        types: [on-demand-testflight]
env:
 VERSION: "1.3.0"
jobs:
  updateSchema:
    name: Retrieve new Schema.json
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: neuroid-ios-sdk
          
      - name: Checkout schema
        uses: actions/checkout@v3  
        with:
          repository: Neuro-ID/nid-event-schema
          token: ${{ secrets.SCHEMA_PAT }}
          path: schema
          
      - name: Update Internal Library
        run: |
            ls neuroid-ios-sdk/
            ls schema/
            cp schema/src/schema.json neuroid-ios-sdk/NeuroID/

  test:
    runs-on: macos-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v3
        
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
         ruby-version: 2.7.2
        
      - name: Bundle Install
        run: bundle install
        
      - name: Get last version from tags
        run: |
         git fetch --prune --unshallow
         echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
         
      - uses: actions/cache@v2
        with:
         path: Pods
         key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
         restore-keys: |
          ${{ runner.os }}-pods-
      
      - name: CocoaPod Install
        run: pod install
        
      - name: Run iOS Unit testing for SDK
        run: bundle exec fastlane test
        
      - name: Running iOS native Sandbox actions
        run: |
             curl \
                -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.API_TOKEN_GITHUB }}" \
                https://api.github.com/repos/Neuro-ID/neuroid-ios-sdk-sandbox/dispatches \
                -d '{"event_type":"on-demand-testflight","client_payload":{"version":"4.ios-${{env.VERSION}}", "message": "${{ github.event.head_commit.message }}"}}'
        
      - name: Running ReactNative Sandbox actions
        run: |
             curl \
                -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.API_TOKEN_GITHUB }}" \
                https://api.github.com/repos/Neuro-ID/neuroid-reactnative-sdk/dispatches \
                -d '{"event_type":"on-demand-testflight","client_payload":{"version":"4.ios-${{env.VERSION}}", "message": "${{ github.event.head_commit.message }}"}}'
