name: Github Actions for iOS NeuroID SDK Staging

on:
  push:
    branches:
      - release/*/*
      
  repository_dispatch:
        types: [on-demand-testflight-staging]
env:
 VERSION: "2.0.0"
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v3
        
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
         ruby-version: 2.7.2
        
      - name: Bundle Install
        run: bundle install
        
      - name: Get last version from tags
        run: |
         git fetch --prune --unshallow
         echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
         
      - uses: actions/cache@v2
        with:
         path: Pods
         key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
         restore-keys: |
          ${{ runner.os }}-pods-
      
      - name: CocoaPod Install
        run: pod install
        
      - name: Run iOS Unit testing for SDK STAGING
        run: bundle exec fastlane test
        
      - name: Running iOS native Sandbox actions STAGING
        run: |
             curl \
                -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.API_TOKEN_GITHUB }}" \
                https://api.github.com/repos/Neuro-ID/neuroid-ios-sdk-sandbox/dispatches \
                -d '{"event_type":"on-demand-testflight-staging","client_payload":{"version":"4.ios-${{env.VERSION}}", "message": "${{ github.event.head_commit.message }}"}}'
      
      - name: Send Slack Notification on Failure
          if: ${{ failure() }}
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: mobile-sdk-tech-team
            SLACK_COLOR: ${{ job.status }}
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_MESSAGE: "Failed execution on master iOS sdk build"
            SLACK_TITLE: Failed release iOS SDK
            SLACK_USERNAME: rtBot
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
