name: Github Actions for iOS NeuroID SDK

on:
  push:
    branches:
      - main
      - master
      - 'ENG-17-github-actions-for-neuroid-ios-sdk'
      
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v3
        
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
         ruby-version: 2.7.2
        
      - name: Bundle Install
        run: bundle install
        
      - uses: actions/cache@v2
        with:
         path: Pods
         key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
         restore-keys: |
          ${{ runner.os }}-pods-
      - name: CocoaPod Install
        run: pod install
        
      - name: Run iOS Unit testing for SDK
        run: bundle exec fastlane test
