on:
  workflow_dispatch:
    inputs:
      version_checker:
        description: 'Enter title'
        required: true
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $version" | grep -Po '(?<=divider-bin-)[^;]+'
        env:
          version: ${{ inputs.version_checker }}

