name: Pull request version check

on:
  workflow_dispatch:
    inputs:
      version_checker:
        description: 'Enter title'
        required: true
        type: string
env:
 VERSION: "-1"
jobs:
  versionCheck:
    name: Pull request version number validation
    runs-on: ubuntu-latest
    steps:
      - name: Get the version number
        run: |
          v=`echo $version | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/'`
          echo "Version number $v"
          if [ "$version" = "$v" ]; then
            echo "VERSION="-1"" >> $GITHUB_ENV
          else
            echo "VERSION=$v" >> $GITHUB_ENV
          fi
        env:
          version: ${{ inputs.version_checker }}
        
      - name: Show new version
        run: echo $VERSION
        
  createTags:
   name: Create tag and release
   if: $VERSION != "-1"
   steps:
     - name: Create tag to last commit
       run: |
          echo "update podspec"
          echo "update xcode version"
          echo "Commit version"
          echo "Create tag to last commit"
          echo "Create release"
          echo "Run test"
       
  
