name: Pull request version check

on:
  workflow_dispatch:
    inputs:
      version_checker:
        description: 'Enter title'
        required: true
        type: string

jobs:
  versionCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version number
      - run: |
          v=`echo $version | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/'`
          echo "Version number $v"
          if [ "$version" = "$v" ]; then
              export version_number="-1"
              echo "::set-env name=version_number::$version_number"
          else
              export version_number=$v
              echo "::set-env name=version_number::$version_number"
          fi
        env:
          version: ${{ inputs.version_checker }}
        
      - name: Show new version
      - run: |
          echo "varaible = $version_number"

