name: Pull request version check

on:
  workflow_dispatch:
    inputs:
      version_checker:
        description: 'Enter title'
        required: true
        type: string
jobs:
  versionCheck:
    name: Pull request version number validation
    runs-on: ubuntu-latest
    outputs:
        version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        name: Get the version number
        run: |
          v=`echo $version | sed 's/^.*[^0-9]\([0-9]*\.[0-9]*\.[0-9]*\).*$/\1/'`
          if [ "$version" = "$v" ]; then
            echo "version="-1"" >> $GITHUB_OUTPUT
          else
            echo "version=$v" >> $GITHUB_OUTPUT
          fi
          echo "Version number ${{ steps.version.outputs.version }}"
        env:
          version: ${{ inputs.version_checker }}
        
  createTags:
   runs-on: ubuntu-latest
   name: Create tag and release
   if: needs.versionCheck.outputs.version != '-1' 
   steps:
     - name: Create tag to last commit
       run: |
          echo "${{ needs.versionCheck.outputs.version }}"
          echo "update podspec"
          echo "update xcode version"
          echo "Commit version"
          echo "Create tag to last commit"
          echo "Create release"
          echo "Run test"
       
  
