# ******************************************************************
# This workflow will trigger once the `version-update.yaml` workflow PR is complete
# or a PR goes into main from a branch that has a prefix of `releases/`
# ******************************************************************

name: Release SDK Version Post PR

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

env: 
  SVC_NAME: "neuroid-ios-sdk"

jobs:
  releaseProjectVersion:
    runs-on: macos-15
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'releases/')
    name: Create Release from Tag
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up ruby env
        uses: ruby/setup-ruby@8aeb6ff8030dd539317f8e1769a044873b56ea71
        with:
          ruby-version: 3.4.7
          bundler-cache: true

      - name: Get Updated Version
        run: |
          PACKAGE_VERSION=$(bundle exec fastlane get_project_version | grep -o "SDK Version:.*" | sed "s/SDK Version: //" )
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/github-script@v5
        with:
          script: |
            const name = 'Release Version: ${{ env.PACKAGE_VERSION }}';
            const body = 'SDK Version ${{ env.PACKAGE_VERSION }}';

            const createRelease = async () => {
                await github.rest.repos.createRelease({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    tag_name: 'v${{ env.PACKAGE_VERSION }}',
                    name: name,
                    body: body,
                    draft: false,
                    prerelease: false,
                    generate_release_notes: true
                });

                console.log(`Release created`);
            }
            createRelease();

      - name: Update Release to also have "Latest" Tag
        run: |
          git config --global user.email developer@neuro-id.com
          git config --global user.name neuroid-developer
          set +e
          git push origin :latest
          git tag -d latest
          git tag latest
          git push origin latest
          set -e

      - name: Release to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push NeuroID.podspec --allow-warnings

      - name: Send Release Succeeded Result to iOS SwiftUI Sandbox Repo
        if: success()
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GPR_API_KEY }}" \
            https://api.github.com/repos/Neuro-ID/neuroid-ios-sdk-sandbox-swiftui/dispatches \
            -d '{"event_type":"release","client_payload":{"release_successful":true}}'

      - name: Send Release Failure Result to iOS SwiftUI Sandbox Repo
        if: failure()
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GPR_API_KEY }}" \
            https://api.github.com/repos/Neuro-ID/neuroid-ios-sdk-sandbox-swiftui/dispatches \
            -d '{"event_type":"release","client_payload":{"release_successful":false}}'
